services:
  selenoid_chrome:
    image: selenoid/chrome:128.0
    container_name: selenoid_chrome
    ports:
      - "4444:4444"
    networks:
      - ui_testing_network

  ui_tests:
    build: .
    container_name: ui_autotests
    environment:
      HOME_PAGE: ${HOME_PAGE}
      REGISTRATION_PAGE: ${REGISTRATION_PAGE}
      DRAG_AND_DROP_PAGE: ${DRAG_AND_DROP_PAGE}
      TABS_PAGE: ${TABS_PAGE}
      ALERTS_PAGE: ${ALERTS_PAGE}
      HEADER_PHONE_1: ${HEADER_PHONE_1}
      HEADER_PHONE_2: ${HEADER_PHONE_2}
      HEADER_PHONE_3: ${HEADER_PHONE_3}
      HEADER_SKYPE: ${HEADER_SKYPE}
      HEADER_EMAIL: ${HEADER_EMAIL}
      MENU_ALL_COURSES: ${MENU_ALL_COURSES}
      MENU_VIDEO_TUTORIAL: ${MENU_VIDEO_TUTORIAL}
      MENU_RESOURCES: ${MENU_RESOURCES}
      MENU_CAREERS: ${MENU_CAREERS}
      MENU_LIFETIME_MEMBERSHIP: ${MENU_LIFETIME_MEMBERSHIP}
      MENU_BLOG: ${MENU_BLOG}
      MENU_FORUM: ${MENU_FORUM}
      MENU_MEMBER_LOGIN: ${MENU_MEMBER_LOGIN}
      MENU_ONLINE_TRAINING: ${MENU_ONLINE_TRAINING}
      MENU_CORPORATE_TRAINING: ${MENU_CORPORATE_TRAINING}
      MENU_ALL_COURSES_APPIUM_PYTHON: ${MENU_ALL_COURSES_APPIUM_PYTHON}
      MENU_VIDEO_TUTORIAL_SPRING: ${MENU_VIDEO_TUTORIAL_SPRING}
      LOGIN_PAGE: ${LOGIN_PAGE}
      LOGIN_USERNAME: ${LOGIN_USERNAME}
      LOGIN_PASSWORD: ${LOGIN_PASSWORD}
      BASIC_AUTH_PAGE: ${BASIC_AUTH_PAGE}
      BASIC_AUTH_USERNAME: ${BASIC_AUTH_USERNAME}
      BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD}
      AUTH_COOKIES_PAGE: ${AUTH_COOKIES_PAGE}
      AUTH_COOKIES_USERNAME: ${AUTH_COOKIES_USERNAME}
      AUTH_COOKIES_PASSWORD: ${AUTH_COOKIES_PASSWORD}
      ALT_AUTH_COOKIES_PAGE: ${ALT_AUTH_COOKIES_PAGE}
      ALT_AUTH_COOKIES_LOGGED_PAGE: ${ALT_AUTH_COOKIES_LOGGED_PAGE}
      ALT_AUTH_COOKIES_USERNAME: ${ALT_AUTH_COOKIES_USERNAME}
      ALT_AUTH_COOKIES_PASSWORD: ${ALT_AUTH_COOKIES_PASSWORD}

    command: pytest -n 7 --disable-warnings --alluredir=/ui_tests/allure-results --clean-alluredir
    volumes:
      - .:/ui_tests
    depends_on:
      selenoid_chrome:
        condition: service_started
    networks:
      - ui_testing_network

networks:
  ui_testing_network:
    driver: bridge
